### ISSUE TITLE
Automate populating key vault secrets required by solution(s)

### ISSUE THREAD

**Issue by mikedzikowski** [mikedzikowski/logicapps#6]
There may be a need to automate the creation of secrets in the referenced kv for the following:
sas
djuser
dj
vmuser
vmpw 

`$SasToken = (Get-AzKeyVaultSecret -VaultName $KeyVault -Name "sas" -AsPlainText)

$DomainJoinUser= (Get-AzKeyVaultSecret -VaultName $KeyVault -Name "djuser" -AsPlainText)

$DomainJoinPassword =  (Get-AzKeyVaultSecret -VaultName $KeyVault -Name "dj" -AsPlainText)

$vmUser =  (Get-AzKeyVaultSecret -VaultName $KeyVault -Name "vmuser" -AsPlainText)

$vmPassword =  (Get-AzKeyVaultSecret -VaultName $KeyVault -Name "vmpw" -AsPlainText)`

**Comment by jamasten** [comment]
why plain text?

**Comment by jamasten** [comment]
Check this out: https://github.com/jamasten/Azure/blob/30fc014fa22a05831a00820df507c30646f0f621/solutions/avdDiskShrink/artifacts/Set-FslogixDiskShrinkVirtualMachine.ps1#L67

**Comment by mikedzikowski** [comment]
> Check this out: https://github.com/jamasten/Azure/blob/30fc014fa22a05831a00820df507c30646f0f621/solutions/avdDiskShrink/artifacts/Set-FslogixDiskShrinkVirtualMachine.ps1#L67

I've updated the code to use .SecretValue. PlainText was for initial testing and troubleshooting.

**Comment by mikedzikowski** [comment]
completed
